// Code generated by MockGen. DO NOT EDIT.
// Source: auth-service/internal/domain (interfaces: AuthRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/fx/auth_repository_mock_test.go -package=appfx auth-service/internal/domain AuthRepository
//

// Package appfx is a generated GoMock package.
package appfx

import (
	auth "auth-service/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthRepository) Create(ctx context.Context, params auth.CreateCredentialParams) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthRepository)(nil).Create), ctx, params)
}

// CreateRefreshToken mocks base method.
func (m *MockAuthRepository) CreateRefreshToken(ctx context.Context, params auth.CreateRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) CreateRefreshToken(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateRefreshToken), ctx, params)
}

// RotateRefreshToken mocks base method.
func (m *MockAuthRepository) RotateRefreshToken(ctx context.Context, params auth.RotateRefreshTokenParams) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, params)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) RotateRefreshToken(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).RotateRefreshToken), ctx, params)
}

// RevokeRefreshToken mocks base method.
func (m *MockAuthRepository) RevokeRefreshToken(ctx context.Context, params auth.RevokeRefreshTokenParams) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, params)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockAuthRepositoryMockRecorder) RevokeRefreshToken(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockAuthRepository)(nil).RevokeRefreshToken), ctx, params)
}

// CreateVerificationCode mocks base method.
func (m *MockAuthRepository) CreateVerificationCode(ctx context.Context, params auth.CreateVerificationCodeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerificationCode", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVerificationCode indicates an expected call of CreateVerificationCode.
func (mr *MockAuthRepositoryMockRecorder) CreateVerificationCode(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerificationCode", reflect.TypeOf((*MockAuthRepository)(nil).CreateVerificationCode), ctx, params)
}

// DeactivateRegistrationAuth mocks base method.
func (m *MockAuthRepository) DeactivateRegistrationAuth(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateRegistrationAuth", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateRegistrationAuth indicates an expected call of DeactivateRegistrationAuth.
func (mr *MockAuthRepositoryMockRecorder) DeactivateRegistrationAuth(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateRegistrationAuth", reflect.TypeOf((*MockAuthRepository)(nil).DeactivateRegistrationAuth), ctx, userID)
}

// DeleteByUserID mocks base method.
func (m *MockAuthRepository) DeleteByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockAuthRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockAuthRepository)(nil).DeleteByUserID), ctx, userID)
}

// ExistsByEmail mocks base method.
func (m *MockAuthRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockAuthRepositoryMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockAuthRepository)(nil).ExistsByEmail), ctx, email)
}

// GetByUserID mocks base method.
func (m *MockAuthRepository) GetByUserID(ctx context.Context, userID string) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAuthRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAuthRepository)(nil).GetByUserID), ctx, userID)
}

// GetByIdentifier mocks base method.
func (m *MockAuthRepository) GetByIdentifier(ctx context.Context, identifier string) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdentifier", ctx, identifier)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdentifier indicates an expected call of GetByIdentifier.
func (mr *MockAuthRepositoryMockRecorder) GetByIdentifier(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdentifier", reflect.TypeOf((*MockAuthRepository)(nil).GetByIdentifier), ctx, identifier)
}

// ListRolesByUserID mocks base method.
func (m *MockAuthRepository) ListRolesByUserID(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolesByUserID indicates an expected call of ListRolesByUserID.
func (mr *MockAuthRepositoryMockRecorder) ListRolesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolesByUserID", reflect.TypeOf((*MockAuthRepository)(nil).ListRolesByUserID), ctx, userID)
}

// VerifyRegistrationEmail mocks base method.
func (m *MockAuthRepository) VerifyRegistrationEmail(ctx context.Context, userID, tokenHash string, now time.Time) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistrationEmail", ctx, userID, tokenHash, now)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistrationEmail indicates an expected call of VerifyRegistrationEmail.
func (mr *MockAuthRepositoryMockRecorder) VerifyRegistrationEmail(ctx, userID, tokenHash, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistrationEmail", reflect.TypeOf((*MockAuthRepository)(nil).VerifyRegistrationEmail), ctx, userID, tokenHash, now)
}
