// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-auth-service/internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-auth-service/internal/application/type.go -aux_files auth-service/internal/domain=/home/alex/projects/ofm-microservices/ofm-auth-service/internal/domain/auth.go,auth-service/internal/infra=/home/alex/projects/ofm-microservices/ofm-auth-service/internal/infra/type.go -destination=/home/alex/projects/ofm-microservices/ofm-auth-service/internal/application/mock_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	domain "auth-service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockAuthService) CreateCredential(ctx context.Context, userID, email, passwordHash string) (*domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, userID, email, passwordHash)
	ret0, _ := ret[0].(*domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockAuthServiceMockRecorder) CreateCredential(ctx, userID, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockAuthService)(nil).CreateCredential), ctx, userID, email, passwordHash)
}

// CreatePendingRegistration mocks base method.
func (m *MockAuthService) CreatePendingRegistration(ctx context.Context, userID, email, passwordHash string) (*domain.PendingRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingRegistration", ctx, userID, email, passwordHash)
	ret0, _ := ret[0].(*domain.PendingRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePendingRegistration indicates an expected call of CreatePendingRegistration.
func (mr *MockAuthServiceMockRecorder) CreatePendingRegistration(ctx, userID, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingRegistration", reflect.TypeOf((*MockAuthService)(nil).CreatePendingRegistration), ctx, userID, email, passwordHash)
}

// DeleteCredential mocks base method.
func (m *MockAuthService) DeleteCredential(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockAuthServiceMockRecorder) DeleteCredential(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockAuthService)(nil).DeleteCredential), ctx, userID)
}

// ExistsByEmail mocks base method.
func (m *MockAuthService) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockAuthServiceMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockAuthService)(nil).ExistsByEmail), ctx, email)
}
