// Code generated by MockGen. DO NOT EDIT.
// Source: auth-service/internal/application (interfaces: AuthService)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock_test.go -package=service auth-service/internal/application AuthService
//

// Package service is a generated GoMock package.
package service

import (
	auth "auth-service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockAuthService) CreateCredential(ctx context.Context, userID, email, username, passwordHash string) (*auth.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, userID, email, username, passwordHash)
	ret0, _ := ret[0].(*auth.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockAuthServiceMockRecorder) CreateCredential(ctx, userID, email, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockAuthService)(nil).CreateCredential), ctx, userID, email, username, passwordHash)
}

// CreatePendingRegistration mocks base method.
func (m *MockAuthService) CreatePendingRegistration(ctx context.Context, userID, email, username, passwordHash string) (*auth.PendingRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingRegistration", ctx, userID, email, username, passwordHash)
	ret0, _ := ret[0].(*auth.PendingRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePendingRegistration indicates an expected call of CreatePendingRegistration.
func (mr *MockAuthServiceMockRecorder) CreatePendingRegistration(ctx, userID, email, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingRegistration", reflect.TypeOf((*MockAuthService)(nil).CreatePendingRegistration), ctx, userID, email, username, passwordHash)
}

// DeactivateRegistrationAuth mocks base method.
func (m *MockAuthService) DeactivateRegistrationAuth(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateRegistrationAuth", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateRegistrationAuth indicates an expected call of DeactivateRegistrationAuth.
func (mr *MockAuthServiceMockRecorder) DeactivateRegistrationAuth(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateRegistrationAuth", reflect.TypeOf((*MockAuthService)(nil).DeactivateRegistrationAuth), ctx, userID)
}

// DeleteCredential mocks base method.
func (m *MockAuthService) DeleteCredential(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockAuthServiceMockRecorder) DeleteCredential(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockAuthService)(nil).DeleteCredential), ctx, userID)
}

// ExistsByEmail mocks base method.
func (m *MockAuthService) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockAuthServiceMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockAuthService)(nil).ExistsByEmail), ctx, email)
}

// IssueRegistrationTokens mocks base method.
func (m *MockAuthService) IssueRegistrationTokens(ctx context.Context, userID string) (*auth.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRegistrationTokens", ctx, userID)
	ret0, _ := ret[0].(*auth.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRegistrationTokens indicates an expected call of IssueRegistrationTokens.
func (mr *MockAuthServiceMockRecorder) IssueRegistrationTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRegistrationTokens", reflect.TypeOf((*MockAuthService)(nil).IssueRegistrationTokens), ctx, userID)
}

// VerifyRegistrationEmail mocks base method.
func (m *MockAuthService) VerifyRegistrationEmail(ctx context.Context, userID, code string) (*auth.RegistrationEmailVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistrationEmail", ctx, userID, code)
	ret0, _ := ret[0].(*auth.RegistrationEmailVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistrationEmail indicates an expected call of VerifyRegistrationEmail.
func (mr *MockAuthServiceMockRecorder) VerifyRegistrationEmail(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistrationEmail", reflect.TypeOf((*MockAuthService)(nil).VerifyRegistrationEmail), ctx, userID, code)
}
